### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by xsuperbug** [volkandindar/agartha#2]
Hi,

My burp version is  : v2022.3.8

During installation, I got the following error:

`java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.har.a(Unknown Source)
	at burp.har.<init>(Unknown Source)
	at burp.imo.a(Unknown Source)
	at burp._1.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)`

Could you help me about this, please?

Thanks.

**Comment by volkandindar** [comment]
Hello again,

I tried to replicate the same issue but no hope so far.

the error might be an environmental issue.
Could you run other Jython extensions without any problems?

and i also made some online searches and the my conclusion is:
	* re-install app: burp, java.
	* re-setting up Jython: Extender -> Options -> Python Environment 'jython-standalone.jar' path
	* re-load the extension

Please let me know if you have any progess.

**Comment by volkandindar** [comment]
Closing the issue since there was no answer.
